spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category_product_db
    username: springStudent
    password: springStudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080
